name: Build my QMK configuration

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */2 *' # run every two months to keep artifacts from expiring
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: meetlab/kafkasplit
          keymap: default
          local-keymap-path: keymaps/default
          output-dir: qmk-firmware-dilemma
      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: qmk-firmware-dilemma

  keymap_images:
    needs: build
    permissions:
      contents: write
    uses: ./.github/workflows/draw_keymaps.yaml
    with:
      artifact_name: "keymap_layouts"
#      parse_args: "charybdis: '-b keymap-drawer/charybdis.yaml'"
      config_path: "keymap-drawer/config.yaml"
